### ISSUE TITLE
DTLS ServerKeyExchange failure

### ISSUE THREAD

**Issue by ghost** [webrtc-rs/dtls#15]
Could anyone help me out here? I am attempting to set up connectivity of a WebRTC-rs client DataChannel with https://github.com/naia-rs/naia-socket ... and it appears that the DTLS handshake is failing on the ServerKeyExchange message given, exactly here: https://github.com/webrtc-rs/dtls/blob/main/src/handshake/handshake_message_server_key_exchange.rs#L114 The message indicates that the incoming signature will be something like ~19000 bytes, but the incoming message size is only ~300 bytes ... curious.

The failing message is created/written by an openssl::SslAcceptor which is created here: https://github.com/kyren/webrtc-unreliable/blob/master/src/crypto.rs#L56

I have created an example repo to demonstrate this behavior here: https://github.com/naia-rs/naia-socket-webrtc-rs-example, you should be able to reproduce this pretty quite using this repo.

I suspect a DTLS version mismatch here? Does anyone know how I can check the version of DTLS being used to read/write messages in both openssl & webrtc-rs/dtls?

Thank you so much for any help!

webrtc-rs main issue: https://github.com/webrtc-rs/webrtc/issues/163
naia-socket issue:    https://github.com/naia-rs/naia-socket/issues/56

**Comment by melekes** [comment]
> Does anyone know how I can check the version of DTLS being used to read/write messages in both openssl & webrtc-rs/dtls?

Have you tried inspecting packets with wireshark. I personally found it very useful.

**Comment by naia-rs** [comment]
Thanks for the idea melekes, I will try that out

**Comment by robashton** [comment]
Sadly this one *wasn’t* fixed with my change - I pulled this code to take a look and it is failing in flight1

i actually suspect the culprit is in webrtc-unreliable, but I didn’t have time to dig further yet
